services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    image: sihingbenni/dons-flow:latest
    container_name: web
    env_file:
      - apps/backend/.env.docker
    ports:
      - "4000:4000"

volumes:
  mongo_data:
