services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    env_file:
      - apps/frontend/.env
      - apps/backend/.env
    ports:
      - "3000:3000"
      - "4000:4000"

volumes:
  mongo_data:
