services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    env_file:
      - apps/frontend/.env.docker
      - apps/backend/.env.docker
    ports:
      - "3000:3000"
      - "4000:4000"

volumes:
  mongo_data:
