@base_url = http://localhost:4000/api
@token = 
@email = 
@video_id =
@note_id = 
@flashcard_id = 

### test api ###
GET {{base_url}}




### AUTH ###
### login ###
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "{{email}}"
}

### authenticate ###
GET {{base_url}}/auth/authenticate?stytch_token_type=magic_links&token={{token}}

### status ###
GET {{base_url}}/auth/status

### logout ###
POST {{base_url}}/auth/logout




### VIDEO ###
### process video ###
POST {{base_url}}/video
Content-Type: application/json

{
  "videoUrl": "https://www.youtube.com/watch?v=iP6XpLQM2Cs"
}

### get all user videos ###
GET {{base_url}}/video
Content-Type: application/json

### get video ###
GET {{base_url}}/video/{{video_id}}




### NOTES ###
### get notes for specific video of user ###
GET {{base_url}}/video/{{video_id}}/notes
Content-Type: application/json

### get note of specific video of user ###
GET {{base_url}}/video/{{video_id}}/notes/{{note_id}}
Content-Type: application/json

### create note for specific video of user ###
POST {{base_url}}/video/{{video_id}}/notes
Content-Type: application/json

{
    "note": {
      "moment": 10,
      "text": "This is a note for the beginning of the video"
    }
}

### patch a note for specific video of user ###
PATCH {{base_url}}/video/{{video_id}}/notes/{{note_id}}
Content-Type: application/json

{
  "moment": 100
}

### update a note for specific video of user ###
PUT {{base_url}}/video/{{video_id}}/notes/{{note_id}}
Content-Type: application/json

{
  "moment": 0,
  "text": "This is a note for the beginning of the video"
}

### delete a note for specific video of user ###
DELETE {{base_url}}/video/{{video_id}}/notes/{{note_id}}




### FLASHCARDS ###
### get user flashcards for specific video ###
GET {{base_url}}/video/{{video_id}}/flashcards
Content-Type: application/json

### get flashcard of specific video of user ###
GET {{base_url}}/video/{{video_id}}/flashcards/{{flashcard_id}}
Content-Type: application/json

### create flashcard for specific video of user ###
POST {{base_url}}/video/{{video_id}}/flashcards
Content-Type: application/json

{
    "flashcard": {
        "front": "What is the capital of France?",
        "back": "Champs-Élysées"
    }
}

### patch a flashcard for specific video of user ###
PATCH {{base_url}}/video/{{video_id}}/flashcards/{{flashcard_id}}
Content-Type: application/json

{
  "back": "Paris"
}

### update a flashcard for specific video of user ###
PUT {{base_url}}/video/{{video_id}}/flashcards/{{flashcard_id}}
Content-Type: application/json

{
  "front": "What is the capital of France?",
  "back": "Champs-Élysées"
}

### delete a flashcard for specific video of user ###
DELETE {{base_url}}/video/{{video_id}}/flashcards/{{flashcard_id}}




### QUIZ ###
### create quiz for specific video of user ###
POST {{base_url}}/video/{{video_id}}/quiz
Content-Type: application/json

{
    "start": 0,
    "end": 320,
    "type": "open"
}

### validate answer ###
POST {{base_url}}/video/{{video_id}}/quiz/validate
Content-Type: application/json

{
    "answer": "When you have data and closely associated behavior or if you know you're going to need multiple instances.",
		"userAnswer": "on tuesday",
		"question": "According to the transcript, what is one scenario where using a class is justified instead of a function?"
}

