@base_url = http://localhost:4000/api
@token = KWkfCIQT8eIy8Cix_rfjcO2jdni5z5oJCWTaSdMF4Haf
@email = jose.acevesgon@gmail.com 
### test api ###
GET {{base_url}}


### login ###
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "{{email}}"
}

### authenticate ###
GET {{base_url}}/auth/authenticate?stytch_token_type=magic_links&token={{token}}

### status ###
GET {{base_url}}/auth/status


### logout ###
POST {{base_url}}/auth/logout


